events {}
http {
    # THIS is the block NGINX couldn't find!
    upstream frontend_pool {
        server web_server_0:80;
        server web_server_1:80;
    }

    server {
        listen 80;

        # 1. Main Website Traffic -> Secure Python Frontend
        location / {
            proxy_pass http://frontend_pool;
        }

        # 2. Grafana Traffic
        location /grafana/ {
            proxy_set_header Host $http_host;
            proxy_pass http://grafana_server:3000/;
        }

        # 3. Prometheus Traffic
        location /prometheus/ {
            proxy_pass http://prometheus_server:9090/prometheus/;
        }
    }
}
