events {
    worker_connections 1024;
}

http {
    # This is the secret ingredient for Docker networking
    resolver 127.0.0.11 valid=5s;

    upstream frontend_pool {
        server web_server_0:80;
        server web_server_1:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_pool;
        }

	location /grafana/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Script-Name /grafana;
            
            # Remove the trailing slash here to ensure paths are passed correctly
            proxy_pass http://grafana_server:3000;
        }

        location /prometheus/ {
            proxy_pass http://prometheus_server:9090;
        }
    }
}
