events {}
http {
    upstream web_backend {
        server frontend_server_0:80;
        server frontend_server_1:80;
    }
    
    server {
        listen 80;
        
        # 1. Your Python App
        location / {
            proxy_pass http://web_backend;
        }

        # 2. Grafana Dashboard
        # The trailing slash on :3000/ is critical here!
        location /grafana/ {
            proxy_pass http://grafana_server:3000/;
            proxy_set_header Host $http_host;
        }

        # 3. Prometheus Data
        # The trailing slash on :9090/ is critical here!
        location /prometheus/ {
            proxy_pass http://prometheus_server:9090/;
        }
    }
}
